// Mock episode data with full content for MVP
import type { EpisodeMeta, EpisodeContent } from './types';

// 12 episodes per level, first 3 unlocked
export const episodesMeta: EpisodeMeta[] = [
  // BEGINNER LEVEL (12 episodes)
  {
    id: 'b1',
    title: 'Morning Coffee Conversations',
    description: 'Learn everyday vocabulary through casual morning conversations about coffee, breakfast, and starting the day.',
    level: 'beginner',
    duration: 480,
    audioUrl: '/audio/b1.mp3',
    thumbnail: '/thumbnails/coffee.jpg',
    category: 'Daily Life',
    isNew: true,
    isLocked: false,
    order: 1,
  },
  {
    id: 'b2',
    title: 'Ordering at a Restaurant',
    description: 'Essential phrases for ordering food, asking about the menu, and paying the bill.',
    level: 'beginner',
    duration: 540,
    audioUrl: '/audio/b2.mp3',
    thumbnail: '/thumbnails/restaurant.jpg',
    category: 'Daily Life',
    isLocked: false,
    order: 2,
  },
  {
    id: 'b3',
    title: 'Shopping for Clothes',
    description: 'Vocabulary and phrases for shopping, asking about sizes, colors, and prices.',
    level: 'beginner',
    duration: 420,
    audioUrl: '/audio/b3.mp3',
    thumbnail: '/thumbnails/shopping.jpg',
    category: 'Daily Life',
    isLocked: false,
    order: 3,
  },
  {
    id: 'b4',
    title: 'Asking for Directions',
    description: 'Learn how to ask for and give directions in English.',
    level: 'beginner',
    duration: 390,
    audioUrl: '/audio/b4.mp3',
    thumbnail: '/thumbnails/directions.jpg',
    category: 'Travel',
    isLocked: true,
    order: 4,
  },
  {
    id: 'b5',
    title: 'At the Doctor\'s Office',
    description: 'Medical vocabulary and phrases for describing symptoms.',
    level: 'beginner',
    duration: 510,
    audioUrl: '/audio/b5.mp3',
    thumbnail: '/thumbnails/doctor.jpg',
    category: 'Health',
    isLocked: true,
    order: 5,
  },
  {
    id: 'b6',
    title: 'Making Phone Calls',
    description: 'Essential phrases for phone conversations and leaving messages.',
    level: 'beginner',
    duration: 450,
    audioUrl: '/audio/b6.mp3',
    thumbnail: '/thumbnails/phone.jpg',
    category: 'Communication',
    isLocked: true,
    order: 6,
  },
  {
    id: 'b7',
    title: 'Weather Talk',
    description: 'Discussing the weather and making small talk.',
    level: 'beginner',
    duration: 360,
    audioUrl: '/audio/b7.mp3',
    thumbnail: '/thumbnails/weather.jpg',
    category: 'Daily Life',
    isLocked: true,
    order: 7,
  },
  {
    id: 'b8',
    title: 'Family and Friends',
    description: 'Vocabulary for describing family members and relationships.',
    level: 'beginner',
    duration: 480,
    audioUrl: '/audio/b8.mp3',
    thumbnail: '/thumbnails/family.jpg',
    category: 'Relationships',
    isLocked: true,
    order: 8,
  },
  {
    id: 'b9',
    title: 'Daily Routines',
    description: 'Talking about your daily schedule and habits.',
    level: 'beginner',
    duration: 420,
    audioUrl: '/audio/b9.mp3',
    thumbnail: '/thumbnails/routine.jpg',
    category: 'Daily Life',
    isLocked: true,
    order: 9,
  },
  {
    id: 'b10',
    title: 'Hobbies and Interests',
    description: 'Expressing your hobbies and asking about others\' interests.',
    level: 'beginner',
    duration: 510,
    audioUrl: '/audio/b10.mp3',
    thumbnail: '/thumbnails/hobbies.jpg',
    category: 'Lifestyle',
    isLocked: true,
    order: 10,
  },
  {
    id: 'b11',
    title: 'Numbers and Prices',
    description: 'Understanding and using numbers in everyday situations.',
    level: 'beginner',
    duration: 390,
    audioUrl: '/audio/b11.mp3',
    thumbnail: '/thumbnails/numbers.jpg',
    category: 'Daily Life',
    isLocked: true,
    order: 11,
  },
  {
    id: 'b12',
    title: 'Time and Dates',
    description: 'Telling time and discussing schedules and appointments.',
    level: 'beginner',
    duration: 450,
    audioUrl: '/audio/b12.mp3',
    thumbnail: '/thumbnails/time.jpg',
    category: 'Daily Life',
    isLocked: true,
    order: 12,
  },

  // INTERMEDIATE LEVEL (12 episodes)
  {
    id: 'i1',
    title: 'At the Airport',
    description: 'Essential phrases and vocabulary for navigating airports, checking in, and boarding flights.',
    level: 'intermediate',
    duration: 720,
    audioUrl: '/audio/i1.mp3',
    thumbnail: '/thumbnails/airport.jpg',
    category: 'Travel',
    isLocked: false,
    order: 1,
  },
  {
    id: 'i2',
    title: 'Technology and Social Media',
    description: 'Modern vocabulary related to technology, apps, social media, and digital communication.',
    level: 'intermediate',
    duration: 660,
    audioUrl: '/audio/i2.mp3',
    thumbnail: '/thumbnails/technology.jpg',
    category: 'Technology',
    isLocked: false,
    order: 2,
  },
  {
    id: 'i3',
    title: 'Job Interviews',
    description: 'Prepare for job interviews with common questions and professional vocabulary.',
    level: 'intermediate',
    duration: 780,
    audioUrl: '/audio/i3.mp3',
    thumbnail: '/thumbnails/interview.jpg',
    category: 'Business',
    isLocked: false,
    order: 3,
  },
  {
    id: 'i4',
    title: 'Health and Fitness',
    description: 'Discussing health habits, gym routines, and wellness.',
    level: 'intermediate',
    duration: 600,
    audioUrl: '/audio/i4.mp3',
    thumbnail: '/thumbnails/fitness.jpg',
    category: 'Health',
    isLocked: true,
    order: 4,
  },
  {
    id: 'i5',
    title: 'Environment and Climate',
    description: 'Vocabulary for discussing environmental issues and sustainability.',
    level: 'intermediate',
    duration: 720,
    audioUrl: '/audio/i5.mp3',
    thumbnail: '/thumbnails/environment.jpg',
    category: 'Science',
    isLocked: true,
    order: 5,
  },
  {
    id: 'i6',
    title: 'Movies and Entertainment',
    description: 'Discussing films, TV shows, and giving opinions.',
    level: 'intermediate',
    duration: 540,
    audioUrl: '/audio/i6.mp3',
    thumbnail: '/thumbnails/movies.jpg',
    category: 'Entertainment',
    isLocked: true,
    order: 6,
  },
  {
    id: 'i7',
    title: 'Travel Stories',
    description: 'Sharing travel experiences and describing places.',
    level: 'intermediate',
    duration: 660,
    audioUrl: '/audio/i7.mp3',
    thumbnail: '/thumbnails/travel.jpg',
    category: 'Travel',
    isLocked: true,
    order: 7,
  },
  {
    id: 'i8',
    title: 'Cooking and Recipes',
    description: 'Food vocabulary and explaining cooking processes.',
    level: 'intermediate',
    duration: 600,
    audioUrl: '/audio/i8.mp3',
    thumbnail: '/thumbnails/cooking.jpg',
    category: 'Lifestyle',
    isLocked: true,
    order: 8,
  },
  {
    id: 'i9',
    title: 'News and Current Events',
    description: 'Understanding and discussing news topics.',
    level: 'intermediate',
    duration: 720,
    audioUrl: '/audio/i9.mp3',
    thumbnail: '/thumbnails/news.jpg',
    category: 'News',
    isLocked: true,
    order: 9,
  },
  {
    id: 'i10',
    title: 'Banking and Finance',
    description: 'Managing money, banking services, and financial vocabulary.',
    level: 'intermediate',
    duration: 540,
    audioUrl: '/audio/i10.mp3',
    thumbnail: '/thumbnails/banking.jpg',
    category: 'Business',
    isLocked: true,
    order: 10,
  },
  {
    id: 'i11',
    title: 'Sports and Competition',
    description: 'Talking about sports, teams, and athletic events.',
    level: 'intermediate',
    duration: 600,
    audioUrl: '/audio/i11.mp3',
    thumbnail: '/thumbnails/sports.jpg',
    category: 'Sports',
    isLocked: true,
    order: 11,
  },
  {
    id: 'i12',
    title: 'Education and Learning',
    description: 'Discussing education systems and learning experiences.',
    level: 'intermediate',
    duration: 660,
    audioUrl: '/audio/i12.mp3',
    thumbnail: '/thumbnails/education.jpg',
    category: 'Education',
    isLocked: true,
    order: 12,
  },

  // ADVANCED LEVEL (12 episodes)
  {
    id: 'a1',
    title: 'Business Negotiations',
    description: 'Advanced vocabulary for negotiations, persuasion, and professional communication.',
    level: 'advanced',
    duration: 900,
    audioUrl: '/audio/a1.mp3',
    thumbnail: '/thumbnails/negotiations.jpg',
    category: 'Business',
    isLocked: false,
    order: 1,
  },
  {
    id: 'a2',
    title: 'Academic Debates',
    description: 'Critical thinking vocabulary and how to construct arguments.',
    level: 'advanced',
    duration: 840,
    audioUrl: '/audio/a2.mp3',
    thumbnail: '/thumbnails/debate.jpg',
    category: 'Education',
    isLocked: false,
    order: 2,
  },
  {
    id: 'a3',
    title: 'Legal English',
    description: 'Understanding legal terminology and processes.',
    level: 'advanced',
    duration: 960,
    audioUrl: '/audio/a3.mp3',
    thumbnail: '/thumbnails/legal.jpg',
    category: 'Business',
    isLocked: false,
    order: 3,
  },
  {
    id: 'a4',
    title: 'Medical Terminology',
    description: 'Advanced medical vocabulary and healthcare discussions.',
    level: 'advanced',
    duration: 900,
    audioUrl: '/audio/a4.mp3',
    thumbnail: '/thumbnails/medical.jpg',
    category: 'Health',
    isLocked: true,
    order: 4,
  },
  {
    id: 'a5',
    title: 'Scientific Research',
    description: 'Vocabulary for discussing research and scientific methods.',
    level: 'advanced',
    duration: 840,
    audioUrl: '/audio/a5.mp3',
    thumbnail: '/thumbnails/research.jpg',
    category: 'Science',
    isLocked: true,
    order: 5,
  },
  {
    id: 'a6',
    title: 'Philosophy and Ethics',
    description: 'Abstract concepts and philosophical discussions.',
    level: 'advanced',
    duration: 780,
    audioUrl: '/audio/a6.mp3',
    thumbnail: '/thumbnails/philosophy.jpg',
    category: 'Education',
    isLocked: true,
    order: 6,
  },
  {
    id: 'a7',
    title: 'Politics and Governance',
    description: 'Political vocabulary and discussing government systems.',
    level: 'advanced',
    duration: 900,
    audioUrl: '/audio/a7.mp3',
    thumbnail: '/thumbnails/politics.jpg',
    category: 'News',
    isLocked: true,
    order: 7,
  },
  {
    id: 'a8',
    title: 'Art and Culture',
    description: 'Discussing art, cultural movements, and artistic expression.',
    level: 'advanced',
    duration: 720,
    audioUrl: '/audio/a8.mp3',
    thumbnail: '/thumbnails/art.jpg',
    category: 'Entertainment',
    isLocked: true,
    order: 8,
  },
  {
    id: 'a9',
    title: 'Economics and Markets',
    description: 'Economic concepts and market analysis vocabulary.',
    level: 'advanced',
    duration: 840,
    audioUrl: '/audio/a9.mp3',
    thumbnail: '/thumbnails/economics.jpg',
    category: 'Business',
    isLocked: true,
    order: 9,
  },
  {
    id: 'a10',
    title: 'Psychology and Behavior',
    description: 'Understanding human behavior and psychological concepts.',
    level: 'advanced',
    duration: 780,
    audioUrl: '/audio/a10.mp3',
    thumbnail: '/thumbnails/psychology.jpg',
    category: 'Science',
    isLocked: true,
    order: 10,
  },
  {
    id: 'a11',
    title: 'Literature Analysis',
    description: 'Analyzing literary works and discussing themes.',
    level: 'advanced',
    duration: 900,
    audioUrl: '/audio/a11.mp3',
    thumbnail: '/thumbnails/literature.jpg',
    category: 'Education',
    isLocked: true,
    order: 11,
  },
  {
    id: 'a12',
    title: 'Technology and AI',
    description: 'Discussing artificial intelligence and future technology.',
    level: 'advanced',
    duration: 840,
    audioUrl: '/audio/a12.mp3',
    thumbnail: '/thumbnails/ai.jpg',
    category: 'Technology',
    isLocked: true,
    order: 12,
  },
];

// Sample episode content for "Morning Coffee Conversations" (b1)
export const sampleEpisodeContent: EpisodeContent = {
  episodeId: 'b1',
  transcript: [
    { id: 't1', startTime: 0, endTime: 5, text: "Good morning! Would you like some coffee?", speaker: "Sarah" },
    { id: 't2', startTime: 5, endTime: 10, text: "Yes, please. I take mine with milk and sugar.", speaker: "John" },
    { id: 't3', startTime: 10, endTime: 16, text: "How about you? Do you prefer black coffee?", speaker: "John" },
    { id: 't4', startTime: 16, endTime: 22, text: "Actually, I prefer black coffee. No sugar for me. It helps me wake up faster.", speaker: "Sarah" },
    { id: 't5', startTime: 22, endTime: 28, text: "I see. Have you had breakfast yet?", speaker: "John" },
    { id: 't6', startTime: 28, endTime: 35, text: "Not yet. I usually just grab a quick bite on my way to work.", speaker: "Sarah" },
    { id: 't7', startTime: 35, endTime: 42, text: "That's not very healthy. Breakfast is the most important meal of the day!", speaker: "John" },
    { id: 't8', startTime: 42, endTime: 50, text: "You're right. Maybe I should start waking up earlier.", speaker: "Sarah" },
  ],
  expressions: [
    {
      id: 'e1',
      phrase: "I take mine with...",
      meaning: "Used to describe how you prefer your drink (coffee, tea, etc.)",
      example: "I take mine with two sugars and a splash of milk.",
      type: 'expression',
    },
    {
      id: 'e2',
      phrase: "grab a quick bite",
      meaning: "To eat something quickly, usually a small meal or snack",
      example: "I don't have time for lunch, so I'll just grab a quick bite.",
      type: 'idiom',
    },
    {
      id: 'e3',
      phrase: "on my way to",
      meaning: "While traveling to a destination",
      example: "I'll pick up the groceries on my way to home.",
      type: 'expression',
    },
    {
      id: 'e4',
      phrase: "wake up",
      meaning: "To stop sleeping and become alert (phrasal verb)",
      example: "I usually wake up at 7 AM on weekdays.",
      type: 'phrasal_verb',
    },
  ],
  vocabulary: [
    {
      id: 'v1',
      word: "coffee",
      pronunciation: "/ˈkɔːfi/",
      partOfSpeech: "noun",
      definition: "A hot drink made from roasted coffee beans",
      example: "Would you like a cup of coffee?",
    },
    {
      id: 'v2',
      word: "breakfast",
      pronunciation: "/ˈbrekfəst/",
      partOfSpeech: "noun",
      definition: "The first meal of the day, usually eaten in the morning",
      example: "I had eggs and toast for breakfast.",
    },
    {
      id: 'v3',
      word: "prefer",
      pronunciation: "/prɪˈfɜːr/",
      partOfSpeech: "verb",
      definition: "To like one thing more than another",
      example: "I prefer tea to coffee.",
    },
    {
      id: 'v4',
      word: "healthy",
      pronunciation: "/ˈhelθi/",
      partOfSpeech: "adjective",
      definition: "Good for your body and mind",
      example: "Eating vegetables is healthy.",
    },
    {
      id: 'v5',
      word: "usually",
      pronunciation: "/ˈjuːʒuəli/",
      partOfSpeech: "adverb",
      definition: "Most of the time; normally",
      example: "I usually wake up at 7 AM.",
    },
  ],
  quiz: [
    {
      id: 'q1',
      question: "How does John take his coffee?",
      options: ["Black, no sugar", "With milk and sugar", "With cream only", "He doesn't drink coffee"],
      correctAnswer: 1,
      explanation: "John says 'I take mine with milk and sugar.'",
    },
    {
      id: 'q2',
      question: "Why does Sarah prefer black coffee?",
      options: ["It tastes better", "It helps her wake up faster", "She's allergic to milk", "It's cheaper"],
      correctAnswer: 1,
      explanation: "Sarah says black coffee 'helps me wake up faster.'",
    },
    {
      id: 'q3',
      question: "What does 'grab a quick bite' mean?",
      options: ["To bite someone quickly", "To eat something quickly", "To grab food with your hands", "To skip a meal"],
      correctAnswer: 1,
      explanation: "'Grab a quick bite' is an idiom meaning to eat something quickly.",
    },
    {
      id: 'q4',
      question: "Has Sarah had breakfast yet?",
      options: ["Yes, she had eggs", "Yes, she had coffee", "No, not yet", "The conversation doesn't say"],
      correctAnswer: 2,
      explanation: "Sarah says 'Not yet' when asked about breakfast.",
    },
    {
      id: 'q5',
      question: "According to John, what is the most important meal of the day?",
      options: ["Lunch", "Dinner", "Breakfast", "Snacks"],
      correctAnswer: 2,
      explanation: "John says 'Breakfast is the most important meal of the day!'",
    },
    {
      id: 'q6',
      question: "What does Sarah usually do for breakfast?",
      options: ["Cooks a big meal", "Skips it completely", "Grabs a quick bite on her way to work", "Eats at a restaurant"],
      correctAnswer: 2,
      explanation: "Sarah says she usually 'grabs a quick bite on my way to work.'",
    },
    {
      id: 'q7',
      question: "What does 'I take mine with...' refer to?",
      options: ["Taking something away", "How you prefer your drink", "Taking medicine", "A type of coffee"],
      correctAnswer: 1,
      explanation: "This expression is used to describe how you prefer your drink.",
    },
    {
      id: 'q8',
      question: "What might Sarah do to have a proper breakfast?",
      options: ["Eat less", "Sleep more", "Wake up earlier", "Drink more coffee"],
      correctAnswer: 2,
      explanation: "Sarah says 'Maybe I should start waking up earlier.'",
    },
    {
      id: 'q9',
      question: "What is the opposite of 'healthy'?",
      options: ["Wealthy", "Unhealthy", "Happy", "Tired"],
      correctAnswer: 1,
      explanation: "The opposite of 'healthy' is 'unhealthy.'",
    },
    {
      id: 'q10',
      question: "Which word means 'most of the time'?",
      options: ["Always", "Never", "Usually", "Sometimes"],
      correctAnswer: 2,
      explanation: "'Usually' means most of the time or normally.",
    },
  ],
  aiPrompts: [
    {
      id: 'ai1',
      question: "Describe your morning routine. What do you usually have for breakfast?",
      expectedTopics: ['morning', 'breakfast', 'routine', 'wake up', 'eat'],
      difficulty: 'easy',
    },
    {
      id: 'ai2',
      question: "How do you take your coffee or tea? Do you prefer hot or cold drinks in the morning?",
      expectedTopics: ['coffee', 'tea', 'prefer', 'drink', 'morning'],
      difficulty: 'easy',
    },
    {
      id: 'ai3',
      question: "Do you think breakfast is the most important meal of the day? Why or why not?",
      expectedTopics: ['breakfast', 'important', 'healthy', 'meal', 'opinion'],
      difficulty: 'medium',
    },
  ],
};

// Get episode content by ID (for now returns sample for b1, empty for others)
export const getEpisodeContent = (episodeId: string): EpisodeContent | null => {
  if (episodeId === 'b1') {
    return sampleEpisodeContent;
  }
  // Return placeholder for other episodes
  return null;
};

// Get episodes by level
export const getEpisodesByLevel = (level: 'beginner' | 'intermediate' | 'advanced'): EpisodeMeta[] => {
  return episodesMeta.filter(ep => ep.level === level).sort((a, b) => a.order - b.order);
};

// Get unlocked episodes
export const getUnlockedEpisodes = (): EpisodeMeta[] => {
  return episodesMeta.filter(ep => !ep.isLocked);
};
